# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fde98b0c4b428e7a1ac5948342175d2c05c3c1395a062e19e2460cbc0c233ca6b53ff502a1b2fc3c8e94ed085e19583d9f45d2bb4bb0d283a08a23f695ce139

test:
  secret_key_base: 69a05dd5b1738c3c10cfe41a2a7536e5861fbce02f3da64d44408ac04c5a11017687387315b3aeb9bfe2e73fedf7e3596a750850e74b4b99464a46b31b1b77f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
